---
- name: Add Nginx GPG Key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add official Nginx repository
  apt_repository:
    repo: "deb http://nginx.org/packages/ubuntu/ jammy nginx"
    state: present

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx